## Word Based Neural Language Model

The training of the network
involves providing sequences of words as input that are processed one at a time where a prediction
can be made and learned for each input sequence. Similarly, when making predictions, the
process can be seeded with one or a few words, then predicted words can be gathered and
presented as input on subsequent predictions in order to build up a generated output sequence
Therefore, each model will involve splitting the source text into input and output sequences,
such that the model can learn to predict words. There are many ways to frame the sequences
from a source text for language modeling


In [20]:
# source text
data = """ Jack and Jill went up the hill\n
To fetch a pail of water\n
Jack fell down and broke his crown\n
And Jill came tumbling after\n """

### Model 1: One-Word-In, One-Word-Out Sequences

In [21]:
def encode_text(txt):
    tokenizer =Tokenizer()
    tokenizer.fit_on_texts([txt])
    encoded = tokenizer.texts_to_sequences([txt])[0]
    return encoded, len(tokenizer.word_index) + 1,tokenizer

In [22]:
# Create word sequence

def create_word_seq(encoded):
    encoded_seq = list()
    for i in range(1,len(encoded)):
        encoded_seq.append(encoded[i-1:i+1])
    print('Total Sequences', encoded_seq)
    return encoded_seq

In [23]:
def build_model(vocab_size):
    model = Sequential()
    model.add(Embedding(vocab_size,10,input_length=1))
    model.add(LSTM(100))
    model.add(Dense(vocab_size,activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.summary()
    return model

In [24]:
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
# generate a sequence from the mode

In [25]:
encoded_txt,vocab_size,tokenizer = encode_text(data)

encoded_seq = create_word_seq(encoded_txt)

encoded_seq = array(encoded_seq)

X,y = encoded_seq[:,:-1],encoded_seq[:,-1]

# One hot encoding outputs
y = to_categorical(y,num_classes=vocab_size)

model = build_model(vocab_size)

model.fit(X,y,epochs=1000)

Total Sequences [[2, 1], [1, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 2], [2, 14], [14, 15], [15, 1], [1, 16], [16, 17], [17, 18], [18, 1], [1, 3], [3, 19], [19, 20], [20, 21]]
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 1, 10)             220       
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               44400     
_________________________________________________________________
dense_2 (Dense)              (None, 22)                2222      
Total params: 46,842
Trainable params: 46,842
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 18s 18s/step - loss: 3.0910 - accuracy: 0.0417
Epoch 2/1000
1/1 [==============================]

1/1 [==============================] - 0s 50ms/step - loss: 2.9106 - accuracy: 0.1250
Epoch 71/1000
1/1 [==============================] - 0s 34ms/step - loss: 2.9041 - accuracy: 0.1250
Epoch 72/1000
1/1 [==============================] - 0s 70ms/step - loss: 2.8973 - accuracy: 0.1250
Epoch 73/1000
1/1 [==============================] - 0s 36ms/step - loss: 2.8904 - accuracy: 0.1250
Epoch 74/1000
1/1 [==============================] - 0s 37ms/step - loss: 2.8832 - accuracy: 0.1250
Epoch 75/1000
1/1 [==============================] - 0s 34ms/step - loss: 2.8759 - accuracy: 0.1250
Epoch 76/1000
1/1 [==============================] - 0s 35ms/step - loss: 2.8683 - accuracy: 0.1250
Epoch 77/1000
1/1 [==============================] - 0s 33ms/step - loss: 2.8606 - accuracy: 0.1250
Epoch 78/1000
1/1 [==============================] - 0s 41ms/step - loss: 2.8526 - accuracy: 0.1250
Epoch 79/1000
1/1 [==============================] - 0s 34ms/step - loss: 2.8444 - accuracy: 0.1250
Epoch 80/1000


1/1 [==============================] - 0s 64ms/step - loss: 1.7177 - accuracy: 0.7083
Epoch 151/1000
1/1 [==============================] - 0s 32ms/step - loss: 1.6978 - accuracy: 0.7083
Epoch 152/1000
1/1 [==============================] - 0s 39ms/step - loss: 1.6780 - accuracy: 0.7083
Epoch 153/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.6583 - accuracy: 0.7083
Epoch 154/1000
1/1 [==============================] - 0s 31ms/step - loss: 1.6386 - accuracy: 0.7500
Epoch 155/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.6189 - accuracy: 0.7500
Epoch 156/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.5994 - accuracy: 0.7500
Epoch 157/1000
1/1 [==============================] - 0s 29ms/step - loss: 1.5799 - accuracy: 0.7500
Epoch 158/1000
1/1 [==============================] - 0s 28ms/step - loss: 1.5605 - accuracy: 0.7500
Epoch 159/1000
1/1 [==============================] - ETA: 0s - loss: 1.5413 - accuracy: 0.75 - 0s 35ms/st

1/1 [==============================] - 0s 26ms/step - loss: 0.5613 - accuracy: 0.8750
Epoch 231/1000
1/1 [==============================] - 0s 42ms/step - loss: 0.5539 - accuracy: 0.8750
Epoch 232/1000
1/1 [==============================] - 0s 33ms/step - loss: 0.5466 - accuracy: 0.8750
Epoch 233/1000
1/1 [==============================] - 0s 35ms/step - loss: 0.5395 - accuracy: 0.8750
Epoch 234/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5326 - accuracy: 0.8750
Epoch 235/1000
1/1 [==============================] - 0s 28ms/step - loss: 0.5258 - accuracy: 0.8750
Epoch 236/1000
1/1 [==============================] - 0s 42ms/step - loss: 0.5191 - accuracy: 0.8750
Epoch 237/1000
1/1 [==============================] - 0s 36ms/step - loss: 0.5126 - accuracy: 0.8750
Epoch 238/1000
1/1 [==============================] - 0s 31ms/step - loss: 0.5062 - accuracy: 0.8750
Epoch 239/1000
1/1 [==============================] - 0s 24ms/step - loss: 0.5000 - accuracy: 0.8750
Epoch

1/1 [==============================] - 0s 28ms/step - loss: 0.2814 - accuracy: 0.8750
Epoch 311/1000
1/1 [==============================] - 0s 38ms/step - loss: 0.2801 - accuracy: 0.8750
Epoch 312/1000
1/1 [==============================] - 0s 23ms/step - loss: 0.2789 - accuracy: 0.8750
Epoch 313/1000
1/1 [==============================] - 0s 37ms/step - loss: 0.2777 - accuracy: 0.8750
Epoch 314/1000
1/1 [==============================] - ETA: 0s - loss: 0.2765 - accuracy: 0.87 - 0s 30ms/step - loss: 0.2765 - accuracy: 0.8750
Epoch 315/1000
1/1 [==============================] - 0s 36ms/step - loss: 0.2753 - accuracy: 0.8750
Epoch 316/1000
1/1 [==============================] - 0s 32ms/step - loss: 0.2742 - accuracy: 0.8750
Epoch 317/1000
1/1 [==============================] - 0s 26ms/step - loss: 0.2731 - accuracy: 0.8750
Epoch 318/1000
1/1 [==============================] - 0s 30ms/step - loss: 0.2720 - accuracy: 0.8750
Epoch 319/1000
1/1 [==============================] - 0s 27ms/st

1/1 [==============================] - 0s 9ms/step - loss: 0.2293 - accuracy: 0.8750
Epoch 391/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2290 - accuracy: 0.8750
Epoch 392/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2287 - accuracy: 0.8750
Epoch 393/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2284 - accuracy: 0.8750
Epoch 394/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.2281 - accuracy: 0.8750
Epoch 395/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2278 - accuracy: 0.8750
Epoch 396/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.2275 - accuracy: 0.8750
Epoch 397/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2272 - accuracy: 0.8750
Epoch 398/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2270 - accuracy: 0.8750
Epoch 399/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2267 - accuracy: 0.8750
Epoch 400/1000


Epoch 472/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2135 - accuracy: 0.8750
Epoch 473/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.2134 - accuracy: 0.8750
Epoch 474/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2133 - accuracy: 0.8750
Epoch 475/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2132 - accuracy: 0.8750
Epoch 476/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2131 - accuracy: 0.8750
Epoch 477/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2129 - accuracy: 0.8750
Epoch 478/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2128 - accuracy: 0.8750
Epoch 479/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2127 - accuracy: 0.8750
Epoch 480/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2126 - accuracy: 0.8750
Epoch 481/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2125 - accuracy: 0.8750


1/1 [==============================] - 0s 5ms/step - loss: 0.2068 - accuracy: 0.8750
Epoch 554/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2068 - accuracy: 0.8750
Epoch 555/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2067 - accuracy: 0.8750
Epoch 556/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2066 - accuracy: 0.8750
Epoch 557/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2066 - accuracy: 0.8750
Epoch 558/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.2065 - accuracy: 0.8750
Epoch 559/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.2065 - accuracy: 0.8750
Epoch 560/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2064 - accuracy: 0.8750
Epoch 561/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.2064 - accuracy: 0.8750
Epoch 562/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2063 - accuracy: 0.8750
Epoch 563/1000


1/1 [==============================] - 0s 6ms/step - loss: 0.2033 - accuracy: 0.8750
Epoch 635/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2032 - accuracy: 0.8750
Epoch 636/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2032 - accuracy: 0.8750
Epoch 637/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2032 - accuracy: 0.8750
Epoch 638/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2031 - accuracy: 0.8750
Epoch 639/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2031 - accuracy: 0.8750
Epoch 640/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2031 - accuracy: 0.8750
Epoch 641/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2030 - accuracy: 0.8750
Epoch 642/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2030 - accuracy: 0.8750
Epoch 643/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.2030 - accuracy: 0.8750
Epoch 644/1000


1/1 [==============================] - 0s 5ms/step - loss: 0.2011 - accuracy: 0.8750
Epoch 717/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2011 - accuracy: 0.8750
Epoch 718/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2011 - accuracy: 0.8750
Epoch 719/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2011 - accuracy: 0.8750
Epoch 720/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.2010 - accuracy: 0.8750
Epoch 721/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.2010 - accuracy: 0.8750
Epoch 722/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2010 - accuracy: 0.8750
Epoch 723/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2010 - accuracy: 0.8750
Epoch 724/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.2010 - accuracy: 0.8750
Epoch 725/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.2009 - accuracy: 0.8750
Epoch 726/1000


1/1 [==============================] - 0s 7ms/step - loss: 0.1997 - accuracy: 0.8750
Epoch 799/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.1997 - accuracy: 0.8750
Epoch 800/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.1997 - accuracy: 0.8750
Epoch 801/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1997 - accuracy: 0.8750
Epoch 802/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1997 - accuracy: 0.8750
Epoch 803/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.1997 - accuracy: 0.8750
Epoch 804/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1996 - accuracy: 0.8750
Epoch 805/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1996 - accuracy: 0.8750
Epoch 806/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1996 - accuracy: 0.8750
Epoch 807/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1996 - accuracy: 0.8750
Epoch 808/1000


1/1 [==============================] - 0s 8ms/step - loss: 0.1988 - accuracy: 0.8750
Epoch 880/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1988 - accuracy: 0.8750
Epoch 881/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1988 - accuracy: 0.8750
Epoch 882/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.1988 - accuracy: 0.8750
Epoch 883/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1987 - accuracy: 0.8750
Epoch 884/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.1987 - accuracy: 0.8750
Epoch 885/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.1987 - accuracy: 0.8750
Epoch 886/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.1987 - accuracy: 0.8750
Epoch 887/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1987 - accuracy: 0.8750
Epoch 888/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1987 - accuracy: 0.8750
Epoch 889/1000


1/1 [==============================] - 0s 6ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 961/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 962/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 963/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 964/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 965/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 966/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 967/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.1981 - accuracy: 0.8750
Epoch 968/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.1980 - accuracy: 0.8750
Epoch 969/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.1980 - accuracy: 0.8750
Epoch 970/1000


In [30]:
# Generating new Sequences 
def generate_seq(model,tokenizer,seed_txt,n_words):
    in_txt,result = seed_txt,seed_txt
    
    for _ in range(n_words):
        tokens = tokenizer.texts_to_sequences([in_txt])[0]
        
        encoded = array(tokens)
        
        yhat = model.predict_classes(encoded)
        
        out_word = ''
        
        for word,index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        in_txt, result = out_word, result + ' ' + out_word
        
    return result
        
        
        
        

In [31]:
print(generate_seq(model,tokenizer,'jack',6))

C:\Users\saifgazali\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


jack and jill came tumbling after hill


## Model 2: Line-by-Line Sequence

In [33]:
# data preprocessing 

tokenizer = Tokenizer()

tokenizer.fit_on_texts([data])

vocab_size = len(tokenizer.word_index) + 1

seq = list()

for line in data.split('\n'):
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        seq.append(encoded[:i+1])

print(seq)


[[2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 5], [2, 1, 3, 4, 5, 6], [2, 1, 3, 4, 5, 6, 7], [8, 9], [8, 9, 10], [8, 9, 10, 11], [8, 9, 10, 11, 12], [8, 9, 10, 11, 12, 13], [2, 14], [2, 14, 15], [2, 14, 15, 1], [2, 14, 15, 1, 16], [2, 14, 15, 1, 16, 17], [2, 14, 15, 1, 16, 17, 18], [1, 3], [1, 3, 19], [1, 3, 19, 20], [1, 3, 19, 20, 21]]


In [38]:
#Padding input sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = max([len(w) for w in seq])
print(max_length)

sequence = pad_sequences(seq,maxlen=max_length,truncating='pre')

7


In [39]:
print(sequence)

[[ 0  0  0  0  0  2  1]
 [ 0  0  0  0  2  1  3]
 [ 0  0  0  2  1  3  4]
 [ 0  0  2  1  3  4  5]
 [ 0  2  1  3  4  5  6]
 [ 2  1  3  4  5  6  7]
 [ 0  0  0  0  0  8  9]
 [ 0  0  0  0  8  9 10]
 [ 0  0  0  8  9 10 11]
 [ 0  0  8  9 10 11 12]
 [ 0  8  9 10 11 12 13]
 [ 0  0  0  0  0  2 14]
 [ 0  0  0  0  2 14 15]
 [ 0  0  0  2 14 15  1]
 [ 0  0  2 14 15  1 16]
 [ 0  2 14 15  1 16 17]
 [ 2 14 15  1 16 17 18]
 [ 0  0  0  0  0  1  3]
 [ 0  0  0  0  1  3 19]
 [ 0  0  0  1  3 19 20]
 [ 0  0  1  3 19 20 21]]


In [41]:
sequence = array(sequence)
X,y = sequence[:,:-1], sequence[:,-1]

In [42]:
# categorizing 
y = to_categorical(y,num_classes=vocab_size)

In [43]:
model = build_model(vocab_size)

model.fit(X,y,epochs=500)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 1, 10)             220       
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               44400     
_________________________________________________________________
dense_3 (Dense)              (None, 22)                2222      
Total params: 46,842
Trainable params: 46,842
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
1/1 [==============================] - 3s 3s/step - loss: 3.0899 - accuracy: 0.0952
Epoch 2/500
1/1 [==============================] - 0s 10ms/step - loss: 3.0878 - accuracy: 0.0952
Epoch 3/500
1/1 [==============================] - 0s 9ms/step - loss: 3.0857 - accuracy: 0.0952
Epoch 4/500
1/1 [==============================] - 0s 8ms/step - loss: 3.0834 - accuracy:

1/1 [==============================] - 0s 11ms/step - loss: 1.9140 - accuracy: 0.4286
Epoch 70/500
1/1 [==============================] - 0s 12ms/step - loss: 1.8783 - accuracy: 0.4286
Epoch 71/500
1/1 [==============================] - 0s 12ms/step - loss: 1.8430 - accuracy: 0.4286
Epoch 72/500
1/1 [==============================] - 0s 8ms/step - loss: 1.8077 - accuracy: 0.5238
Epoch 73/500
1/1 [==============================] - 0s 7ms/step - loss: 1.7737 - accuracy: 0.5238
Epoch 74/500
1/1 [==============================] - 0s 10ms/step - loss: 1.7413 - accuracy: 0.4762
Epoch 75/500
1/1 [==============================] - 0s 9ms/step - loss: 1.7099 - accuracy: 0.5714
Epoch 76/500
1/1 [==============================] - 0s 9ms/step - loss: 1.6795 - accuracy: 0.6190
Epoch 77/500
1/1 [==============================] - 0s 9ms/step - loss: 1.6501 - accuracy: 0.6190
Epoch 78/500
1/1 [==============================] - 0s 7ms/step - loss: 1.6217 - accuracy: 0.6190
Epoch 79/500
1/1 [===========

1/1 [==============================] - 0s 10ms/step - loss: 0.6518 - accuracy: 0.8095
Epoch 152/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6459 - accuracy: 0.8095
Epoch 153/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6365 - accuracy: 0.8095
Epoch 154/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6287 - accuracy: 0.8095
Epoch 155/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6241 - accuracy: 0.8095
Epoch 156/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6194 - accuracy: 0.8095
Epoch 157/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6124 - accuracy: 0.8095
Epoch 158/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6050 - accuracy: 0.8095
Epoch 159/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6008 - accuracy: 0.8095
Epoch 160/500
1/1 [==============================] - 0s 11ms/step - loss: 0.5962 - accuracy: 0.8095
Epoch 161/500
1/

Epoch 233/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3261 - accuracy: 0.9524
Epoch 234/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3232 - accuracy: 0.9524
Epoch 235/500
1/1 [==============================] - 0s 11ms/step - loss: 0.3206 - accuracy: 0.9524
Epoch 236/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3182 - accuracy: 0.9524
Epoch 237/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3154 - accuracy: 0.9524
Epoch 238/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3128 - accuracy: 0.9524
Epoch 239/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3104 - accuracy: 0.9524
Epoch 240/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3078 - accuracy: 0.9524
Epoch 241/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3052 - accuracy: 0.9524
Epoch 242/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3028 - accuracy: 0.9524
Epoch 2

1/1 [==============================] - 0s 9ms/step - loss: 0.1626 - accuracy: 0.9524
Epoch 316/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1614 - accuracy: 0.9524
Epoch 317/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1601 - accuracy: 0.9524
Epoch 318/500
1/1 [==============================] - 0s 9ms/step - loss: 0.1588 - accuracy: 0.9524
Epoch 319/500
1/1 [==============================] - 0s 11ms/step - loss: 0.1576 - accuracy: 0.9524
Epoch 320/500
1/1 [==============================] - 0s 11ms/step - loss: 0.1564 - accuracy: 0.9524
Epoch 321/500
1/1 [==============================] - 0s 9ms/step - loss: 0.1552 - accuracy: 0.9524
Epoch 322/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1540 - accuracy: 0.9524
Epoch 323/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1529 - accuracy: 0.9524
Epoch 324/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1517 - accuracy: 0.9524
Epoch 325/500
1/1 

Epoch 397/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1024 - accuracy: 0.9524
Epoch 398/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1020 - accuracy: 0.9524
Epoch 399/500
1/1 [==============================] - 0s 12ms/step - loss: 0.1016 - accuracy: 0.9524
Epoch 400/500
1/1 [==============================] - 0s 12ms/step - loss: 0.1013 - accuracy: 0.9524
Epoch 401/500
1/1 [==============================] - 0s 13ms/step - loss: 0.1010 - accuracy: 0.9524
Epoch 402/500
1/1 [==============================] - 0s 10ms/step - loss: 0.1006 - accuracy: 0.9524
Epoch 403/500
1/1 [==============================] - 0s 12ms/step - loss: 0.1003 - accuracy: 0.9524
Epoch 404/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0999 - accuracy: 0.9524
Epoch 405/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0996 - accuracy: 0.9524
Epoch 406/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0993 - accuracy: 0.9524
Ep

Epoch 479/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0844 - accuracy: 0.9524
Epoch 480/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0843 - accuracy: 0.9524
Epoch 481/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0842 - accuracy: 0.9524
Epoch 482/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0840 - accuracy: 0.9524
Epoch 483/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0839 - accuracy: 0.9524
Epoch 484/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0838 - accuracy: 0.9524
Epoch 485/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0837 - accuracy: 0.9524
Epoch 486/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0836 - accuracy: 0.9524
Epoch 487/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0835 - accuracy: 0.9524
Epoch 488/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0833 - accuracy: 0.9524
Epoch 4

In [45]:
def generate_seq(model, tokenizer, max_length, seed_text, n_words):
    in_text = seed_text
    # generate a fixed number of words
    for _ in range(n_words):
        # encode the text as integer
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        # pre-pad sequences to a fixed length
        encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
        # predict probabilities for each word
        yhat = model.predict_classes(encoded, verbose=0)
        # map predicted word index to word
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        # append to input
        in_text += ' ' + out_word
    return in_text
    

In [47]:
print(generate_seq(model, tokenizer, max_length-1, 'Jack', 5))


Jack fell down and broke his


## Model 3: Two-Words-In, One-Word-Out Sequence

We can use an intermediate between the one-word-in and the whole-sentence-in approaches and pass in a sub-sequences of words as input. This will provide a trade-off between the two
framings allowing new lines to be generated and for generation to be picked up mid line. We will
use 3 words as input to predict one word as output

In [52]:
# only the sequence creation will differ from what we had above

tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded_txt = tokenizer.texts_to_sequences([data])[0]

vocab_size = len(tokenizer.word_index) + 1

In [51]:
print(vocab_size)

22


In [53]:
print(encoded_txt)

[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21]


In [55]:
# creating sequences
encoded_seq = list()

for i in range(2,len(encoded_txt)):
    encoded_seq.append(encoded_txt[i-2:i+1])


In [56]:
print(encoded_seq)

[[2, 1, 3], [1, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 10], [9, 10, 11], [10, 11, 12], [11, 12, 13], [12, 13, 2], [13, 2, 14], [2, 14, 15], [14, 15, 1], [15, 1, 16], [1, 16, 17], [16, 17, 18], [17, 18, 1], [18, 1, 3], [1, 3, 19], [3, 19, 20], [19, 20, 21]]


In [58]:
encoded_seq = array(encoded_seq)
X,y = encoded_seq[:,:-1],encoded_seq[:,-1]

In [59]:
print(X)
print(y)

[[ 2  1]
 [ 1  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12 13]
 [13  2]
 [ 2 14]
 [14 15]
 [15  1]
 [ 1 16]
 [16 17]
 [17 18]
 [18  1]
 [ 1  3]
 [ 3 19]
 [19 20]]
[ 3  4  5  6  7  8  9 10 11 12 13  2 14 15  1 16 17 18  1  3 19 20 21]


In [60]:
y = to_categorical(y,num_classes=vocab_size)

In [61]:
model.fit(X,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 2.7815 - accuracy: 0.0870
Epoch 2/500
1/1 [==============================] - 0s 7ms/step - loss: 2.7654 - accuracy: 0.0870
Epoch 3/500
1/1 [==============================] - 0s 9ms/step - loss: 2.7389 - accuracy: 0.0870
Epoch 4/500
1/1 [==============================] - 0s 7ms/step - loss: 2.7047 - accuracy: 0.0870
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 2.6649 - accuracy: 0.1739
Epoch 6/500
1/1 [==============================] - 0s 10ms/step - loss: 2.6209 - accuracy: 0.2174
Epoch 7/500
1/1 [==============================] - 0s 10ms/step - loss: 2.5740 - accuracy: 0.2174
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 2.5253 - accuracy: 0.2174
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 2.4756 - accuracy: 0.3478
Epoch 10/500
1/1 [==============================] - 0s 9ms/step - loss: 2.4255 - accuracy: 0.3478
Epoch 11/500
1/1 [==========

1/1 [==============================] - 0s 9ms/step - loss: 0.4877 - accuracy: 0.9565
Epoch 82/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4732 - accuracy: 0.9565
Epoch 83/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4592 - accuracy: 0.9565
Epoch 84/500
1/1 [==============================] - 0s 10ms/step - loss: 0.4457 - accuracy: 0.9565
Epoch 85/500
1/1 [==============================] - 0s 11ms/step - loss: 0.4325 - accuracy: 0.9565
Epoch 86/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4197 - accuracy: 0.9565
Epoch 87/500
1/1 [==============================] - 0s 33ms/step - loss: 0.4073 - accuracy: 0.9565
Epoch 88/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3952 - accuracy: 0.9565
Epoch 89/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3836 - accuracy: 0.9565
Epoch 90/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3722 - accuracy: 0.9565
Epoch 91/500
1/1 [============

1/1 [==============================] - 0s 10ms/step - loss: 0.0995 - accuracy: 0.9565
Epoch 164/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0989 - accuracy: 0.9565
Epoch 165/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0982 - accuracy: 0.9565
Epoch 166/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0976 - accuracy: 0.9565
Epoch 167/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0970 - accuracy: 0.9565
Epoch 168/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0965 - accuracy: 0.9565
Epoch 169/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0959 - accuracy: 0.9565
Epoch 170/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0954 - accuracy: 0.9565
Epoch 171/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0948 - accuracy: 0.9565
Epoch 172/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0943 - accuracy: 0.9565
Epoch 173/500
1/1 [====

1/1 [==============================] - 0s 9ms/step - loss: 0.0763 - accuracy: 0.9565
Epoch 245/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0761 - accuracy: 0.9565
Epoch 246/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0760 - accuracy: 0.9565
Epoch 247/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0759 - accuracy: 0.9565
Epoch 248/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0758 - accuracy: 0.9565
Epoch 249/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0757 - accuracy: 0.9565
Epoch 250/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0756 - accuracy: 0.9565
Epoch 251/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0754 - accuracy: 0.9565
Epoch 252/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0753 - accuracy: 0.9565
Epoch 253/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0752 - accuracy: 0.9565
Epoch 254/500
1/1 [===

1/1 [==============================] - 0s 8ms/step - loss: 0.0698 - accuracy: 0.9565
Epoch 326/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0698 - accuracy: 0.9565
Epoch 327/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0697 - accuracy: 0.9565
Epoch 328/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0697 - accuracy: 0.9565
Epoch 329/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0696 - accuracy: 0.9565
Epoch 330/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0696 - accuracy: 0.9565
Epoch 331/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0695 - accuracy: 0.9565
Epoch 332/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0695 - accuracy: 0.9565
Epoch 333/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0694 - accuracy: 0.9565
Epoch 334/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0694 - accuracy: 0.9565
Epoch 335/500
1/1 [==

1/1 [==============================] - 0s 11ms/step - loss: 0.0668 - accuracy: 0.9565
Epoch 408/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0668 - accuracy: 0.9565
Epoch 409/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0668 - accuracy: 0.9565
Epoch 410/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0668 - accuracy: 0.9565
Epoch 411/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0667 - accuracy: 0.9565
Epoch 412/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0667 - accuracy: 0.9565
Epoch 413/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0667 - accuracy: 0.9565
Epoch 414/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0667 - accuracy: 0.9565
Epoch 415/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0666 - accuracy: 0.9565
Epoch 416/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0666 - accuracy: 0.9565
Epoch 417/500
1/1 [

1/1 [==============================] - 0s 9ms/step - loss: 0.0652 - accuracy: 0.9565
Epoch 488/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0652 - accuracy: 0.9565
Epoch 489/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0651 - accuracy: 0.9565
Epoch 490/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0651 - accuracy: 0.9565
Epoch 491/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0651 - accuracy: 0.9565
Epoch 492/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0651 - accuracy: 0.9565
Epoch 493/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0651 - accuracy: 0.9565
Epoch 494/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0651 - accuracy: 0.9565
Epoch 495/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0650 - accuracy: 0.9565
Epoch 496/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0650 - accuracy: 0.9565
Epoch 497/500
1/1 [=

In [64]:
print(generate_seq(model, tokenizer, max_length-1, 'Jack and', 5))

Jack and jill jill jill jill the
